<?php
/**
 * 
 * Part of the ZCAdditions Templates Package
 * Provided under GPL 2.0 license by rbarbour (rbarbour@zcadditions.com).
 * Copyright (C) 2013-2018, ZCAdditions. All rights reserved.
 * 
 */
 
// DO NOT EDIT THIS FILE

if (!defined('FOOTERBLOCKS_NUMBER_1')) define('FOOTERBLOCKS_NUMBER_1', '');
if (!defined('FOOTERBLOCKS_NUMBER_2')) define('FOOTERBLOCKS_NUMBER_2', '');
if (!defined('FOOTERBLOCKS_NUMBER_3')) define('FOOTERBLOCKS_NUMBER_3', '');
if (!defined('FOOTERBLOCKS_NUMBER_4')) define('FOOTERBLOCKS_NUMBER_4', '');
if (!defined('FOOTERBLOCKS_NUMBER_5')) define('FOOTERBLOCKS_NUMBER_5', '');
if (!defined('FOOTERBLOCKS_NUMBER_6')) define('FOOTERBLOCKS_NUMBER_6', '');
if (!defined('FOOTERBLOCKS_NUMBER_7')) define('FOOTERBLOCKS_NUMBER_7', '');
if (!defined('FOOTERBLOCKS_NUMBER_8')) define('FOOTERBLOCKS_NUMBER_8', '');
if (!defined('FOOTERBLOCKS_NUMBER_9')) define('FOOTERBLOCKS_NUMBER_9', '');